language: cpp
dist: trusty
matrix:
  include:
  - os: linux
    env: PYTHON=3.5
  - os: linux
    env: PYTHON=3.6
  - os: osx
    env: PYTHON=3.5
  - os: osx
    env: PYTHON=3.6
before_install:
- echo $TRAVIS_OS_NAME
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install python3; fi
- pip install --user --upgrade pip virtualenv
- virtualenv -p python$PYTHON venv
- source venv/bin/activate
install:
- python setup.py sdist
- pip install --verbose dist/*.tar.gz
script:
- make test
